/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univates.banco.apresentacao;

import br.univates.alexandria.Cpf;
import br.univates.alexandria.InvalidEntryException;
import br.univates.alexandria.persistence.IDao;
import br.univates.alexandria.persistence.RecordNotFoundException;
import br.univates.banco.negocio.ContaBancaria;
import br.univates.banco.negocio.Correntista;
import br.univates.banco.persistencia.DaoFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author vini
 */
public class FormMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName());

    /**
     * Creates new form FormMenuPrincipal
     */
    public FormMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemAutoAtendimento = new javax.swing.JMenu();
        itnEntrarConta = new javax.swing.JMenuItem();
        itnCriarConta = new javax.swing.JMenuItem();
        btnListarContas = new javax.swing.JMenuItem();
        Correntista = new javax.swing.JMenu();
        itnMenuCadastrar = new javax.swing.JMenuItem();
        itnMenuEditar = new javax.swing.JMenuItem();
        itnMenuDeletar = new javax.swing.JMenuItem();
        itnListarCorrentistas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        MenuItemAutoAtendimento.setText("Auto Atendimento");
        MenuItemAutoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAutoAtendimentoActionPerformed(evt);
            }
        });

        itnEntrarConta.setText("Gerenciar Conta");
        itnEntrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnEntrarContaActionPerformed(evt);
            }
        });
        MenuItemAutoAtendimento.add(itnEntrarConta);

        itnCriarConta.setText("Criar Conta");
        itnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnCriarContaActionPerformed(evt);
            }
        });
        MenuItemAutoAtendimento.add(itnCriarConta);

        btnListarContas.setText("Listar Contas");
        btnListarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarContasActionPerformed(evt);
            }
        });
        MenuItemAutoAtendimento.add(btnListarContas);

        jMenuBar1.add(MenuItemAutoAtendimento);

        Correntista.setText("Correntista");
        Correntista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrentistaActionPerformed(evt);
            }
        });

        itnMenuCadastrar.setText("Cadastrar");
        itnMenuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnMenuCadastrarActionPerformed(evt);
            }
        });
        Correntista.add(itnMenuCadastrar);

        itnMenuEditar.setText("Editar");
        itnMenuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnMenuEditarActionPerformed(evt);
            }
        });
        Correntista.add(itnMenuEditar);

        itnMenuDeletar.setText("Deletar");
        itnMenuDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnMenuDeletarActionPerformed(evt);
            }
        });
        Correntista.add(itnMenuDeletar);

        itnListarCorrentistas.setText("Listar ");
        itnListarCorrentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnListarCorrentistasActionPerformed(evt);
            }
        });
        Correntista.add(itnListarCorrentistas);

        jMenuBar1.add(Correntista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itnMenuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnMenuCadastrarActionPerformed
        FormCadastrarCorrentista tela = new FormCadastrarCorrentista();
        tela.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_itnMenuCadastrarActionPerformed

    private void itnMenuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnMenuEditarActionPerformed
        String cpf = JOptionPane.showInputDialog("Digite o CPF do correntista: ");
        IDao<Correntista, String> daoCorre = DaoFactory.createCorrentistaDao();

        Correntista corre = null;
        try {
            corre = daoCorre.read(cpf);
        } catch (RecordNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Cpf Inválido", "Message", JOptionPane.ERROR_MESSAGE); 
        
        }
        
        if(corre != null){
            FormEditarCorrentista telaEditar = new FormEditarCorrentista(cpf);
            telaEditar.setVisible(true);
        }
        else{
           JOptionPane.showMessageDialog(this, "Cpf Inválido", "Message", JOptionPane.ERROR_MESSAGE); 
        }
        
        
        
    }//GEN-LAST:event_itnMenuEditarActionPerformed

    private void itnMenuDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnMenuDeletarActionPerformed
        String cpf = JOptionPane.showInputDialog("Digite o CPF do correntista: ");
        IDao<Correntista, String> daoCorre = DaoFactory.createCorrentistaDao();
        try {
            daoCorre.delete(daoCorre.read(cpf));
            JOptionPane.showMessageDialog(this, "Correntista Deletado!", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (RecordNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Correntista não encontrado!", "Message", JOptionPane.ERROR_MESSAGE);

        }
            
        
    }//GEN-LAST:event_itnMenuDeletarActionPerformed

    private void itnEntrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnEntrarContaActionPerformed
        String numeroConta = JOptionPane.showInputDialog("Digite o número da conta: ");
        IDao<ContaBancaria, Integer> daoConta = DaoFactory.createContaBancariaDao();
        try {
            ContaBancaria conta = daoConta.read(Integer.valueOf(numeroConta));
            FormAutoAtendimento tela = new FormAutoAtendimento(conta);
            tela.setVisible(true);
        } catch (RecordNotFoundException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_itnEntrarContaActionPerformed

    private void itnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnCriarContaActionPerformed
        FormCriarConta tela = new FormCriarConta();
        tela.setVisible(true);
        
    }//GEN-LAST:event_itnCriarContaActionPerformed

    private void MenuItemAutoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAutoAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemAutoAtendimentoActionPerformed

    private void itnListarCorrentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnListarCorrentistasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itnListarCorrentistasActionPerformed

    private void btnListarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarContasActionPerformed
        FormListaContas tela = new FormListaContas();
        tela.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarContasActionPerformed

    private void CorrentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrentistaActionPerformed
        FormListaCorrentistas tela = new FormListaCorrentistas();
        tela.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_CorrentistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Correntista;
    private javax.swing.JMenu MenuItemAutoAtendimento;
    private javax.swing.JMenuItem btnListarContas;
    private javax.swing.JMenuItem itnCriarConta;
    private javax.swing.JMenuItem itnEntrarConta;
    private javax.swing.JMenuItem itnListarCorrentistas;
    private javax.swing.JMenuItem itnMenuCadastrar;
    private javax.swing.JMenuItem itnMenuDeletar;
    private javax.swing.JMenuItem itnMenuEditar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
